### ISSUE TITLE
Error occurred prerendering page "/about". Read more: https://nextjs.org/docs/messages/prerender-error

### ISSUE THREAD

**Issue by Rodro1975** [Rodro1975/Soporte-T-cnico-y-Soluciones-Tecnol-gicas#1]
I am encountering an issue with the build process on Vercel for my Next.js project. During the build, I receive the following error related to the /about page:
-
# ReferenceError:
 window is not defined
    at /vercel/path0/.next/server/app/about/page.js:1:19735
    ...
    at /vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:99107

# Steps to Reproduce:

## Clone the repository.
Run npm install to install dependencies.
Run npm run build to build the project.
Expected Behavior: The build process should complete without errors, and the /about page should render correctly.

## Configuration:

Next.js version 14.2.8
Using dynamic imports to handle server-side rendering issues with Leaflet
-
Could anyone provide assistance in resolving this issue? It seems related to the use of window during server-side rendering.

**Comment by Rodro1975** [comment]
Issue Resolved: window is not defined Error During Build Process

The issue regarding the error window is not defined during the build process on Vercel for the /about page has been resolved. The error was related to the use of window during server-side rendering. To fix the issue, we decided to remove the map section that was causing the error and replaced it with a simpler card layout.

Solution:

Removed the map section and replaced it with static cards, eliminating the dependency on window and resolving the server-side rendering issue.
Thank you for your support!
